### ISSUE TITLE
(not issue) confirming it works on my Victus

### ISSUE THREAD

**Issue by ZaidaZadkiel** [Linux-Alex/HP-Victus-sleep-mode-hibernation#1]
OS: Linux Mint 21.3 x86_64 
Host: Victus by HP Gaming Laptop 15-fa1xxx 
Kernel: 6.8.7-2-liquorix-amd64 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: Cinnamon 6.0.4 
WM: Mutter (Muffin) 
CPU: 12th Gen Intel i5-12500H (16) @ 3.101GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 28a0  <-- i still need to fix this, its 4060 mobile
GPU: Intel Alder Lake-P 
Memory: 3431MiB / 63945MiB 

OpenGL renderer string: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 550.67

It works perfectly, thank you

**Comment by Linux-Alex** [comment]
You're welcome! I'm glad to hear that it's working perfectly for you 😄
